name: teamspeak-linux-docker-images
services:
- dockerfile_path: Dockerfile
  github:
    branch: main
    deploy_on_push: true
    repo: TeamSpeak-Systems/teamspeak-linux-docker-images
  name: teamspeak-linux-docker-images
